# This Compose file is meant to be used along the project's `docker-compose.yml`
# file on CI/CD contexts, such as SemaphoreCI or Github Actions.
#
# A useful alias to run this on your CI/CD pipelines:
# `alias ci-compose="docker-compose --file docker-compose.yml --file ci-compose.yml"`
#
# See https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

# We'll use the '3.x spec since it supports the 'cache_from'
# option:
version: '3.7'

volumes:
  node_modules:
  test_coverage:

services:
  tests:
    image: vovimayhem/rails-google-cloud-run-and-tasks${DOCKER_IMAGE_VARIANT:-:testing-latest}
    entrypoint: ${PWD:-/srv/rails-google-cloud-run-and-tasks}/bin/dev-entrypoint
    build: &app_ci_build
      context: .
      target: testing
      args: &app_ci_build_args
        BUILDKIT_INLINE_CACHE: "1"
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
        APP_PATH: ${PWD:-/srv/rails-google-cloud-run-and-tasks}
    depends_on:
      - chrome
    command: rspec
    volumes:
      # Mount the app code into the app container:
      - .:${PWD:-/srv/rails-google-cloud-run-and-tasks}

      # Mount the test coverage volume, so the results persist in this volume:
      - test_coverage:${PWD:-/srv/rails-google-cloud-run-and-tasks}/coverage

      # Replace the binded local node_modules folder with a docker volume:
      - node_modules:${PWD:-/srv/rails-google-cloud-run-and-tasks}/node_modules

    environment:
      RAILS_ENV: test
      
      CHROME_URL: http://chrome:3333
      
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_COMMIT_SHA: ${GIT_COMMIT_SHA}
      GIT_COMMITTED_AT: ${GIT_COMMITTED_AT}

      CC_TEST_REPORTER_ID: 03a1840b0c65eac80ee35ecac9f632736b55acfcc0c598b8542963b915048a73

  release:
    image: vovimayhem/rails-google-cloud-run-and-tasks${DOCKER_IMAGE_VARIANT:-:latest}
    build:
      <<: *app_ci_build
      target: release
      args:
        <<: *app_ci_build_args
        SOURCE_BRANCH: ${GIT_BRANCH}
        SOURCE_COMMIT: ${GIT_COMMIT_SHA}
        BUILD_DATE: ${BUILD_DATE}
        IMAGE_NAME: "vovimayhem/rails-google-cloud-run-and-tasks"
