version: "3.7"

# The application services will be defined at `docker-compose.override.yml`, to
# leave here the service definitions common to the staging and ci/cd environments.

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - ${DEMO_PG_PORT:-5432}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd

  chrome:
    image: browserless/chrome:1.43-chrome-stable
    ports:
      - "3333:3333"
    environment:
      # By default, it uses 3000, which is typically used by Rails.
      PORT: 3333
      # Set connection timeout to avoid timeout exception during debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000
