# This file is an override to the default 'docker-compose.yml' file, and is
# intended to be used in CI contexts (drone, github actions, semaphore, etc).
#
# The most important thing it does is re-uses the services defined in the main
# file (docker-compose.yml) such as postgres, pubsub, etc.
#
# To make it work, be sure you use an alias for docker-compose called
# `staging-compose`. You can create one like this:
# `alias staging-compose="docker-compose --file docker-compose.yml --file staging-compose.yml"`
# our apps:
version: "3.7"

services:
  web: &app
    image: vovimayhem/rails-google-cloud-run-and-tasks:latest

    build:
      context: .
      target: release
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_GID: ${GID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}

    ports:
      - ${DEMO_WEB_PORT:-3000}:3000

    command: puma -e production

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # Specify environment variables available for our app containers. We'll
    # leave a YML anchor in case we need to override or add more variables if
    # needed on each app service:
    environment: &app_environment
      # We'll set the RAILS_ENV and RACK_ENV environment variables to
      # 'production', so our app containers will start in 'production' mode
      # on this compose project:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_LOG_TO_STDOUT: "true"

      SECRET_KEY_BASE: 689b84e285d8cf7f76feec2f21054b74fa014eefcf28da13c06749ca58edd3aafa9575d18da49e6d540d5444914e768b00f2541b3e2563a735d0fbd1a6739432
