
# See also:
# - https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
# - https://cloud.google.com/cloud-build/docs/configuring-builds/use-bash-and-bindings-in-substitutions
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-test-image'
    args:
      - --destination=gcr.io/${PROJECT_ID}/gcp-rails-demo:testing-${BRANCH_NAME//\\/-}
      - --cache=true
      - --cache-ttl=72h
      - --target=installer

  - name: 'docker/compose:1.19.0'
    args: [ '-f', 'docker-compose.yml', '-f', 'ci-compose.yml', 'run', 'test' ]
    env:
      - "GOOGLE_CLOUD_PROJECT=${PROJECT_ID}"
      - "GIT_BRANCH=${BRANCH_NAME}"
      - "GIT_COMMIT_SHA=${COMMIT_SHA}"
    waitFor: ['build-test-image']
