
# See also:
# - https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
# - https://cloud.google.com/cloud-build/docs/configuring-builds/use-bash-and-bindings-in-substitutions
steps:
  - id: 'build-test-image'
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/${PROJECT_ID}/gcp-rails-demo:testing-${_TAG_SAFE_BRANCH}
      - --cache=true
      - --cache-ttl=72h
      - --target=testing

  - id: 'check-workspace'
    name: 'bash'
    args: [ 'pwd' ]

  - id: 'list-workspace-contents'
    name: 'bash'
    waitFor: [ 'check-workspace' ]
    args: [ 'ls', '-lah' ]

  - id: 'run-rspec-tests'
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: [ '-f', 'docker-compose.yml', '-f', 'ci-compose.yml', 'run', 'test' ]
    env:
      - "PROJECT_ID=${PROJECT_ID}"
      - "_TAG_SAFE_BRANCH=${_TAG_SAFE_BRANCH}"
      - "GIT_BRANCH=${BRANCH_NAME}"
      - "GIT_COMMIT_SHA=${COMMIT_SHA}"
    waitFor: [ 'build-test-image' ]
