name: CI & CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Add CI/CD scripts to system path
        run: echo "::add-path::${GITHUB_WORKSPACE}/.github/workflows/bin"

      - name: Normalize env vars
        run: normalize-env-vars

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.4

      - name: Build Test Image
        run: ci-compose build --pull --build-arg BUILDKIT_INLINE_CACHE=1 test
        env:
          # Configures docker-compose to use Docker CLI to build the image:
          COMPOSE_DOCKER_CLI_BUILD: 1
          # Configures Docker CLI to use BuildKit to build the image:
          DOCKER_BUILDKIT: 1
